version: '3.3'

services:
  #Mysql
  mysql:
    image: mysql:5.7
    container_name: students-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - students-system-network
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - students-mysql-data:/docker-entrypoint-initdb.d
      # - students-mysql-data:/data/db
      # - ./mysql/data/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  #Phpmyadmin     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: students-system-phpmyadmin
    ports:
     - 8081:80    
    networks:
      - students-system-network
    depends_on:
      - mysql
    links:
       - mysql:db
    restart: always
    
  #Web Service
  web:
    build: 
      context: ./web/
      dockerfile: Dockerfile
    depends_on: 
      - mysql
    container_name: students-system-web-server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - students-system-network
    ports:
      - 8080:80 
    volumes:
      - type: bind
        source: ./web/src/
        target: /var/www/html/
    restart: always
    links:
      -  mysql:db

# Networks - Volumes - etc.
networks:
  students-system-network:
volumes:
  students-mysql-data:
